### ISSUE TITLE
Video call appears as option in all events

### ISSUE THREAD

**Issue by ProgramRegistration** [supermaxio/CommonGroundProgramRegistration#8]
I'll forward you an email so you can see what I'm talking about. Some people have been confused, thinking there is a video call option for all programs. Ideally, we could remove this, but I know it might be difficult since it's embedded in the google invitation. I have another high-level volunteer I could ask as well, so let me know.

**Comment by supermaxio** [comment]
![githubphotoblanked](https://cloud.githubusercontent.com/assets/15807675/15198856/be2315b0-179f-11e6-98f9-9560bd91acf4.png)

**Comment by supermaxio** [comment]
This might be simple! Will look into it soon and give a timeframe.

**Comment by supermaxio** [comment]
After looking into this issue, it was determined that the scope is beyond the registration app. 

The Google Account Administrator controls video calls being added to events. 

https://support.google.com/a/answer/6188027?hl=en

Moving this issue to closed.
